name: note_app_firebase
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  jiffy: ^5.0.0
  image_picker: ^0.8.5+3
  http: ^0.13.5
  shared_preferences: ^2.0.15
  firebase_core: ^1.24.0
  firebase_storage: ^10.3.11
  cloud_firestore: ^3.5.1
  firebase_messaging: ^13.1.0
  firebase_auth: ^3.11.2
  awesome_dialog: ^3.0.2
  dropdown_search: ^5.0.3
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

